apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cmV6YTEyMzQ=
  MYSQL_DATABASE: bmV3c19kYg==  # Base64 encoded value of 'news_db'
  MYSQL_USER: cm9vdA== 