apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage-class  # স্টোরেজ ক্লাস নাম পরিবর্তন করুন
  nfs:
    server: 192.168.0.108  # আপনার লোকাল মেশিনের IP
    path: /home/imrezaulkrm/Desktop/bartadhara-pv/database  # আপনার NFS শেয়ার করা ডিরেক্টরি

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage-class  # স্টোরেজ ক্লাস নাম পরিবর্তন করুন
  nfs:
    server: 192.168.0.108  # আপনার লোকাল মেশিনের IP
    path: /home/imrezaulkrm/Desktop/bartadhara-pv/backend  # আপনার NFS শেয়ার করা ডিরেক্টরি
