apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/home/imrezaulkrm/Desktop/bartadhara-pv/database"  # হোস্ট মেশিনের ডিরেক্টরি

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/home/imrezaulkrm/Desktop/bartadhara-pv/backend"  # হোস্ট মেশিনের ডিরেক্টরি
